---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "agent.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $.Values.env.secrets }}
  {{ $key }}: {{ $val | b64enc | required (printf "required parameter %s is missing" $key) }}
  {{- end }}
