---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-radar-agent.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-radar-agent.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $.Values.env.secrets }}
  {{ $key }}: {{ required (printf "required secret %s is missing" $key) $val | b64enc }}
  {{- end }}
