# Copyright IBM Corp. 2026

---
{{- if $.Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-radar-agent.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "vault-radar-agent.labels" $ | nindent 4 }}
{{- end }}
